<a href="https://colab.research.google.com/github/ajmalbiju56/ML/blob/main/financialdataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:

df=pd.read_csv('/content/drive/MyDrive/Financial_data.csv')
print(df)

/tmp/ipython-input-2322874972.py:1: DtypeWarning: Columns (34,37,38,80,82,83,89,90) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/drive/MyDrive/Financial_data.csv')

       ReportAsOfEOD                                LoanId  LoanNumber  \
0         2020-01-27  F0660C80-83F3-4A97-8DA0-9C250112D6EC         659
1         2020-01-27  978BB85B-1C69-4D51-8447-9C240104A3A2         654
2         2020-01-27  EA44027E-7FA7-4BB2-846D-9C1F013C8A22         641
3         2020-01-27  CE67AD25-2951-4BEE-96BD-9C2700C61EF4         668
4         2020-01-27  9408BF8C-B159-4D6A-9D61-9C2400A986E3         652
...              ...                                   ...         ...
134524    2020-01-27  A9C9EF0F-4E79-4930-BA8A-A4130077FCC2      283484
134525    2020-01-27  787345C2-7606-4F72-8FE2-A4170082D77C      285168
134526    2020-01-27  E2D3384D-289A-4B4D-A2DA-A40F00F7C755      281602
134527    2020-01-27  7CC7AB74-995B-4467-958A-A41700F78D59      285431
134528    2020-01-27  3A0DEBF3-292C-4EB4-B71A-A4170157749D      285630

                ListedOnUTC     BiddingStartedOn  BidsPortfolioManager  \
0       2009-06-11 16:40:39  2009-06-11 16:40:39                     0
1       2009-06-10 15:48:57  2009-06-10 15:48:57                     0
2       2009-06-05 19:12:29  2009-06-05 19:12:29                     0
3       2009-06-13 12:01:20  2009-06-13 12:01:20                     0
4       2009-06-10 10:17:13  2009-06-10 10:17:13                     0
...                     ...                  ...                   ...
134524  2015-01-02 16:31:36  2015-01-02 16:31:36                  2515
134525  2015-01-05 16:14:26  2015-01-05 16:14:26                  1880
134526  2015-01-02 14:04:27  2015-01-02 14:04:27                  1975
134527  2015-01-05 16:56:12  2015-01-05 16:56:12                  1840
134528  2015-01-06 11:07:06  2015-01-06 11:07:06                  2990

        BidsApi  BidsManual   UserName  NewCreditCustomer  ...  \
0             0    115.0410       KARU               True  ...
1             0    140.6057   koort681              False  ...
2             0    319.5580        0ie               True  ...
3             0     57.5205     Alyona               True  ...
4             0    319.5582        Kai               True  ...
...         ...         ...        ...                ...  ...
134524        0    485.0000  BO73K5A6A               True  ...
134525        0   1120.0000   BO311A49              False  ...
134526        0    525.0000  BO41K639A               True  ...
134527        0   1160.0000   BO45A925              False  ...
134528        0     10.0000  BO152923A              False  ...

       PreviousEarlyRepaymentsCountBeforeLoan GracePeriodStart GracePeriodEnd  \
0                                           0              NaN            NaN
1                                           0              NaN            NaN
2                                           0              NaN            NaN
3                                           0              NaN            NaN
4                                           0              NaN            NaN
...                                       ...              ...            ...
134524                                      0              NaN            NaN
134525                                      0       2017-06-27     2018-06-20
134526                                      0              NaN            NaN
134527                                      0       2016-04-01     2016-10-03
134528                                      0       2015-09-14     2016-03-14

       NextPaymentDate NextPaymentNr NrOfScheduledPayments  ReScheduledOn  \
0                  NaN           NaN                   NaN            NaN
1                  NaN           NaN                   NaN            NaN
2                  NaN           NaN                   NaN            NaN
3                  NaN           NaN                   NaN            NaN
4                  NaN           NaN                   NaN            NaN
...                ...           ...                   ...            ...
134524             NaN           NaN                   NaN            NaN
134525             NaN           NaN                   NaN            NaN
134526             NaN           0.0                  60.0            NaN
134527             NaN           NaN                   NaN            NaN
134528             NaN           0.0                  60.0     2015-09-09

        PrincipalDebtServicingCost  InterestAndPenaltyDebtServicingCost  \
0                              0.0                                 0.00
1                              0.0                                 0.00
2                              0.0                                 0.00
3                              0.0                                 0.00
4                              0.0                                 0.00
...                            ...                                  ...
134524                         0.0                              1040.06
134525                         0.0                                 0.00
134526                         0.0                              1051.85
134527                         0.0                               889.50
134528                         0.0                               604.80

        ActiveLateLastPaymentCategory
0                                 NaN
1                                 NaN
2                                180+
3                                 NaN
4                                180+
...                               ...
134524                           180+
134525                            NaN
134526                           8-15
134527                          31-60
134528                         91-120

[134529 rows x 112 columns]

In [ ]:
df.shape

(134529, 112)

In [ ]:
df.head()

,ReportAsOfEOD,LoanId,LoanNumber,ListedOnUTC,BiddingStartedOn,BidsPortfolioManager,BidsApi,BidsManual,UserName,NewCreditCustomer,...,PreviousEarlyRepaymentsCountBeforeLoan,GracePeriodStart,GracePeriodEnd,NextPaymentDate,NextPaymentNr,NrOfScheduledPayments,ReScheduledOn,PrincipalDebtServicingCost,InterestAndPenaltyDebtServicingCost,ActiveLateLastPaymentCategory
0,2020-01-27,F0660C80-83F3-4A97-8DA0-9C250112D6EC,659,2009-06-11 16:40:39,2009-06-11 16:40:39,0,0,115.0410,KARU,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
1,2020-01-27,978BB85B-1C69-4D51-8447-9C240104A3A2,654,2009-06-10 15:48:57,2009-06-10 15:48:57,0,0,140.6057,koort681,False,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
2,2020-01-27,EA44027E-7FA7-4BB2-846D-9C1F013C8A22,641,2009-06-05 19:12:29,2009-06-05 19:12:29,0,0,319.5580,0ie,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,180+
3,2020-01-27,CE67AD25-2951-4BEE-96BD-9C2700C61EF4,668,2009-06-13 12:01:20,2009-06-13 12:01:20,0,0,57.5205,Alyona,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
4,2020-01-27,9408BF8C-B159-4D6A-9D61-9C2400A986E3,652,2009-06-10 10:17:13,2009-06-10 10:17:13,0,0,319.5582,Kai,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,180+

In [ ]:
df.tail()

,ReportAsOfEOD,LoanId,LoanNumber,ListedOnUTC,BiddingStartedOn,BidsPortfolioManager,BidsApi,BidsManual,UserName,NewCreditCustomer,...,PreviousEarlyRepaymentsCountBeforeLoan,GracePeriodStart,GracePeriodEnd,NextPaymentDate,NextPaymentNr,NrOfScheduledPayments,ReScheduledOn,PrincipalDebtServicingCost,InterestAndPenaltyDebtServicingCost,ActiveLateLastPaymentCategory
134524,2020-01-27,A9C9EF0F-4E79-4930-BA8A-A4130077FCC2,283484,2015-01-02 16:31:36,2015-01-02 16:31:36,2515,0,485.0,BO73K5A6A,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1040.06,180+
134525,2020-01-27,787345C2-7606-4F72-8FE2-A4170082D77C,285168,2015-01-05 16:14:26,2015-01-05 16:14:26,1880,0,1120.0,BO311A49,False,...,0,2017-06-27,2018-06-20,NaN,NaN,NaN,NaN,0.0,0.00,NaN
134526,2020-01-27,E2D3384D-289A-4B4D-A2DA-A40F00F7C755,281602,2015-01-02 14:04:27,2015-01-02 14:04:27,1975,0,525.0,BO41K639A,True,...,0,NaN,NaN,NaN,0.0,60.0,NaN,0.0,1051.85,8-15
134527,2020-01-27,7CC7AB74-995B-4467-958A-A41700F78D59,285431,2015-01-05 16:56:12,2015-01-05 16:56:12,1840,0,1160.0,BO45A925,False,...,0,2016-04-01,2016-10-03,NaN,NaN,NaN,NaN,0.0,889.50,31-60
134528,2020-01-27,3A0DEBF3-292C-4EB4-B71A-A4170157749D,285630,2015-01-06 11:07:06,2015-01-06 11:07:06,2990,0,10.0,BO152923A,False,...,0,2015-09-14,2016-03-14,NaN,0.0,60.0,2015-09-09,0.0,604.80,91-120

In [ ]:
df.describe()

,LoanNumber,BidsPortfolioManager,BidsApi,BidsManual,ApplicationSignedHour,ApplicationSignedWeekday,VerificationType,LanguageCode,Age,Gender,...,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsBefoleLoan,PreviousEarlyRepaymentsCountBeforeLoan,NextPaymentNr,NrOfScheduledPayments,PrincipalDebtServicingCost,InterestAndPenaltyDebtServicingCost
count,1.345290e+05,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134484.000000,134529.000000,134529.000000,134484.000000,...,134529.000000,134529.000000,134529.000000,91368.000000,58026.000000,134529.000000,97788.000000,97788.000000,59129.000000,59129.000000
mean,9.449392e+05,966.452876,29.111664,559.332590,13.374640,3.907908,2.817257,2.827874,40.819295,0.442097,...,701.567107,1.487620,2868.652401,928.395548,320.743805,0.069903,5.178795,50.126795,5.264702,89.851455
std,4.786738e+05,1355.686016,150.159148,750.360512,4.992375,1.726192,1.407908,1.959802,12.348693,0.636083,...,2514.595572,2.396148,4507.046575,2042.348751,1561.799076,0.359461,7.674427,12.519530,57.800582,287.449052
min,3.700000e+01,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,...,-2.660000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,6.206790e+05,155.000000,0.000000,96.000000,10.000000,2.000000,1.000000,1.000000,31.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,36.000000,0.000000,0.000000
50%,9.235970e+05,465.000000,0.000000,317.000000,13.000000,4.000000,4.000000,3.000000,40.000000,0.000000,...,0.000000,1.000000,396.354100,197.980000,0.000000,0.000000,3.000000,60.000000,0.000000,0.000000
75%,1.311025e+06,1218.000000,5.000000,729.000000,17.000000,5.000000,4.000000,4.000000,50.000000,1.000000,...,202.900000,2.000000,4250.000000,780.950000,0.000000,0.000000,7.000000,60.000000,0.000000,17.330000
max,1.855339e+06,10625.000000,7570.000000,10630.000000,23.000000,7.000000,4.000000,22.000000,77.000000,2.000000,...,64494.770000,25.000000,53762.000000,34077.420000,48100.000000,11.000000,60.000000,72.000000,3325.330000,5295.290000

In [ ]:
null_counts = df.isnull().sum()
print(null_counts)

ReportAsOfEOD                              0
LoanId                                     0
LoanNumber                                 0
ListedOnUTC                                0
BiddingStartedOn                           0
                                       ...
NrOfScheduledPayments                  36741
ReScheduledOn                          94207
PrincipalDebtServicingCost             75400
InterestAndPenaltyDebtServicingCost    75400
ActiveLateLastPaymentCategory          82279
Length: 112, dtype: int64

In [ ]:
for col, count in null_counts.items():
    print(f"{col}: {count}")

ReportAsOfEOD: 0
LoanId: 0
LoanNumber: 0
ListedOnUTC: 0
BiddingStartedOn: 0
BidsPortfolioManager: 0
BidsApi: 0
BidsManual: 0
UserName: 0
NewCreditCustomer: 0
LoanApplicationStartedDate: 0
LoanDate: 0
ContractEndDate: 75546
FirstPaymentDate: 0
MaturityDate_Original: 0
MaturityDate_Last: 0
ApplicationSignedHour: 0
ApplicationSignedWeekday: 0
VerificationType: 45
LanguageCode: 0
Age: 0
DateOfBirth: 0
Gender: 45
Country: 0
AppliedAmount: 0
Amount: 0
Interest: 0
LoanDuration: 0
MonthlyPayment: 6685
County: 36840
City: 9794
UseOfLoan: 0
Education: 45
MaritalStatus: 45
NrOfDependants: 98929
EmploymentStatus: 197
EmploymentDurationCurrentEmployer: 876
EmploymentPosition: 98439
WorkExperience: 98007
OccupationArea: 86
HomeOwnershipType: 1652
IncomeFromPrincipalEmployer: 0
IncomeFromPension: 0
IncomeFromFamilyAllowance: 0
IncomeFromSocialWelfare: 0
IncomeFromLeavePay: 0
IncomeFromChildSupport: 0
IncomeOther: 0
IncomeTotal: 0
ExistingLiabilities: 0
LiabilitiesTotal: 0
RefinanceLiabilities: 0
DebtToIncome: 45
FreeCash: 45
MonthlyPaymentDay: 0
ActiveScheduleFirstPaymentReached: 0
PlannedPrincipalTillDate: 80070
PlannedInterestTillDate: 3942
LastPaymentOn: 9531
CurrentDebtDaysPrimary: 86011
DebtOccuredOn: 86011
CurrentDebtDaysSecondary: 82279
DebtOccuredOnForSecondary: 82279
ExpectedLoss: 2636
LossGivenDefault: 2636
ExpectedReturn: 2636
ProbabilityOfDefault: 2636
DefaultDate: 91614
PrincipalOverdueBySchedule: 14837
PlannedPrincipalPostDefault: 91614
PlannedInterestPostDefault: 91614
EAD1: 91614
EAD2: 91614
PrincipalRecovery: 91614
InterestRecovery: 91614
RecoveryStage: 57288
StageActiveSince: 53575
ModelVersion: 2636
Rating: 2730
EL_V0: 129960
Rating_V0: 129960
EL_V1: 121607
Rating_V1: 121607
Rating_V2: 109386
Status: 0
Restructured: 0
ActiveLateCategory: 86011
WorseLateCategory: 45456
CreditScoreEsMicroL: 29574
CreditScoreEsEquifaxRisk: 122310
CreditScoreFiAsiakasTietoRiskGrade: 102011
CreditScoreEeMini: 62807
PrincipalPaymentsMade: 0
InterestAndPenaltyPaymentsMade: 0
PrincipalWriteOffs: 75400
InterestAndPenaltyWriteOffs: 75400
PrincipalBalance: 0
InterestAndPenaltyBalance: 0
NoOfPreviousLoansBeforeLoan: 0
AmountOfPreviousLoansBeforeLoan: 0
PreviousRepaymentsBeforeLoan: 43161
PreviousEarlyRepaymentsBefoleLoan: 76503
PreviousEarlyRepaymentsCountBeforeLoan: 0
GracePeriodStart: 115741
GracePeriodEnd: 115741
NextPaymentDate: 68885
NextPaymentNr: 36741
NrOfScheduledPayments: 36741
ReScheduledOn: 94207
PrincipalDebtServicingCost: 75400
InterestAndPenaltyDebtServicingCost: 75400
ActiveLateLastPaymentCategory: 82279

In [ ]:
# Calculate the percentage of null values per column
null_percentage = df.isnull().mean() * 100

# Filter columns with null percentage 45% or higher
columns_above_45_percent = null_percentage[null_percentage >= 45]

# Print these columns and their null percentages
print(columns_above_45_percent)

ContractEndDate                        56.155922
NrOfDependants                         73.537304
EmploymentPosition                     73.173070
WorkExperience                         72.851950
PlannedPrincipalTillDate               59.518765
CurrentDebtDaysPrimary                 63.934914
DebtOccuredOn                          63.934914
CurrentDebtDaysSecondary               61.160791
DebtOccuredOnForSecondary              61.160791
DefaultDate                            68.099815
PlannedPrincipalPostDefault            68.099815
PlannedInterestPostDefault             68.099815
EAD1                                   68.099815
EAD2                                   68.099815
PrincipalRecovery                      68.099815
InterestRecovery                       68.099815
EL_V0                                  96.603706
Rating_V0                              96.603706
EL_V1                                  90.394636
Rating_V1                              90.394636
Rating_V2                              81.310349
ActiveLateCategory                     63.934914
CreditScoreEsEquifaxRisk               90.917200
CreditScoreFiAsiakasTietoRiskGrade     75.828260
CreditScoreEeMini                      46.686588
PrincipalWriteOffs                     56.047395
InterestAndPenaltyWriteOffs            56.047395
PreviousEarlyRepaymentsBefoleLoan      56.867293
GracePeriodStart                       86.034238
GracePeriodEnd                         86.034238
NextPaymentDate                        51.204573
ReScheduledOn                          70.027280
PrincipalDebtServicingCost             56.047395
InterestAndPenaltyDebtServicingCost    56.047395
ActiveLateLastPaymentCategory          61.160791
dtype: float64

In [ ]:
null_percentage = df.isnull().mean() * 100

# Print each column name with its null value percentage
for col, perc in null_percentage.items():
    print(f"{col}: {perc:.2f}%")

ReportAsOfEOD: 0.00%
LoanId: 0.00%
LoanNumber: 0.00%
ListedOnUTC: 0.00%
BiddingStartedOn: 0.00%
BidsPortfolioManager: 0.00%
BidsApi: 0.00%
BidsManual: 0.00%
UserName: 0.00%
NewCreditCustomer: 0.00%
LoanApplicationStartedDate: 0.00%
LoanDate: 0.00%
ContractEndDate: 56.16%
FirstPaymentDate: 0.00%
MaturityDate_Original: 0.00%
MaturityDate_Last: 0.00%
ApplicationSignedHour: 0.00%
ApplicationSignedWeekday: 0.00%
VerificationType: 0.03%
LanguageCode: 0.00%
Age: 0.00%
DateOfBirth: 0.00%
Gender: 0.03%
Country: 0.00%
AppliedAmount: 0.00%
Amount: 0.00%
Interest: 0.00%
LoanDuration: 0.00%
MonthlyPayment: 4.97%
County: 27.38%
City: 7.28%
UseOfLoan: 0.00%
Education: 0.03%
MaritalStatus: 0.03%
NrOfDependants: 73.54%
EmploymentStatus: 0.15%
EmploymentDurationCurrentEmployer: 0.65%
EmploymentPosition: 73.17%
WorkExperience: 72.85%
OccupationArea: 0.06%
HomeOwnershipType: 1.23%
IncomeFromPrincipalEmployer: 0.00%
IncomeFromPension: 0.00%
IncomeFromFamilyAllowance: 0.00%
IncomeFromSocialWelfare: 0.00%
IncomeFromLeavePay: 0.00%
IncomeFromChildSupport: 0.00%
IncomeOther: 0.00%
IncomeTotal: 0.00%
ExistingLiabilities: 0.00%
LiabilitiesTotal: 0.00%
RefinanceLiabilities: 0.00%
DebtToIncome: 0.03%
FreeCash: 0.03%
MonthlyPaymentDay: 0.00%
ActiveScheduleFirstPaymentReached: 0.00%
PlannedPrincipalTillDate: 59.52%
PlannedInterestTillDate: 2.93%
LastPaymentOn: 7.08%
CurrentDebtDaysPrimary: 63.93%
DebtOccuredOn: 63.93%
CurrentDebtDaysSecondary: 61.16%
DebtOccuredOnForSecondary: 61.16%
ExpectedLoss: 1.96%
LossGivenDefault: 1.96%
ExpectedReturn: 1.96%
ProbabilityOfDefault: 1.96%
DefaultDate: 68.10%
PrincipalOverdueBySchedule: 11.03%
PlannedPrincipalPostDefault: 68.10%
PlannedInterestPostDefault: 68.10%
EAD1: 68.10%
EAD2: 68.10%
PrincipalRecovery: 68.10%
InterestRecovery: 68.10%
RecoveryStage: 42.58%
StageActiveSince: 39.82%
ModelVersion: 1.96%
Rating: 2.03%
EL_V0: 96.60%
Rating_V0: 96.60%
EL_V1: 90.39%
Rating_V1: 90.39%
Rating_V2: 81.31%
Status: 0.00%
Restructured: 0.00%
ActiveLateCategory: 63.93%
WorseLateCategory: 33.79%
CreditScoreEsMicroL: 21.98%
CreditScoreEsEquifaxRisk: 90.92%
CreditScoreFiAsiakasTietoRiskGrade: 75.83%
CreditScoreEeMini: 46.69%
PrincipalPaymentsMade: 0.00%
InterestAndPenaltyPaymentsMade: 0.00%
PrincipalWriteOffs: 56.05%
InterestAndPenaltyWriteOffs: 56.05%
PrincipalBalance: 0.00%
InterestAndPenaltyBalance: 0.00%
NoOfPreviousLoansBeforeLoan: 0.00%
AmountOfPreviousLoansBeforeLoan: 0.00%
PreviousRepaymentsBeforeLoan: 32.08%
PreviousEarlyRepaymentsBefoleLoan: 56.87%
PreviousEarlyRepaymentsCountBeforeLoan: 0.00%
GracePeriodStart: 86.03%
GracePeriodEnd: 86.03%
NextPaymentDate: 51.20%
NextPaymentNr: 27.31%
NrOfScheduledPayments: 27.31%
ReScheduledOn: 70.03%
PrincipalDebtServicingCost: 56.05%
InterestAndPenaltyDebtServicingCost: 56.05%
ActiveLateLastPaymentCategory: 61.16%

In [ ]:
dn = df.loc[:, df.isnull().mean() < 0.45]

In [ ]:
dn.shape

(134529, 77)

In [ ]:
unwanted_columns = ['PlannedPrincipalTillDate','CurrentDebtDaysPrimary','DebtOccuredOn','CurrentDebtDaysSecondary','DebtOccuredOnForSecondary','DefaultDate','PlannedPrincipalPostDefault','PlannedInterestPostDefault','EAD1','EAD2','PrincipalRecovery','EL_V0','InterestRecovery','Rating_V0','EL_V1','Rating_V1','Rating_V2','ActiveLateCategory','CreditScoreEsEquifaxRisk','CreditScoreFiAsiakasTietoRiskGrade','CreditScoreEeMini','PrincipalWriteOffs','InterestAndPenaltyWriteOffs','PreviousEarlyRepaymentsBefoleLoan','GracePeriodStart','GracePeriodEnd','NextPaymentDate','ReScheduledOn','PrincipalDebtServicingCost','InterestAndPenaltyDebtServicingCost','ActiveLateLastPaymentCategory']

# Drop the unwanted columns
df_cleaned = df.drop(columns=unwanted_columns)

# Optional: save the cleaned dataset
df_cleaned.to_csv('cleaned_dataset.csv', index=False)

In [ ]:
df_cleaned.shape

(134529, 81)

In [ ]:
df_cleaned

,ReportAsOfEOD,LoanId,LoanNumber,ListedOnUTC,BiddingStartedOn,BidsPortfolioManager,BidsApi,BidsManual,UserName,NewCreditCustomer,...,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsCountBeforeLoan,NextPaymentNr,NrOfScheduledPayments
0,2020-01-27,F0660C80-83F3-4A97-8DA0-9C250112D6EC,659,2009-06-11 16:40:39,2009-06-11 16:40:39,0,0,115.0410,KARU,True,...,115.0408,20.4222,0.00,0.00,1,83.0852,0.0000,0,NaN,NaN
1,2020-01-27,978BB85B-1C69-4D51-8447-9C240104A3A2,654,2009-06-10 15:48:57,2009-06-10 15:48:57,0,0,140.6057,koort681,False,...,140.6057,2.0227,0.00,0.00,2,255.6467,258.6256,0,NaN,NaN
2,2020-01-27,EA44027E-7FA7-4BB2-846D-9C1F013C8A22,641,2009-06-05 19:12:29,2009-06-05 19:12:29,0,0,319.5580,0ie,True,...,203.1909,59.7626,116.35,414.07,0,0.0000,0.0000,0,NaN,NaN
3,2020-01-27,CE67AD25-2951-4BEE-96BD-9C2700C61EF4,668,2009-06-13 12:01:20,2009-06-13 12:01:20,0,0,57.5205,Alyona,True,...,57.5205,18.7323,0.00,0.00,1,134.2144,0.0000,0,NaN,NaN
4,2020-01-27,9408BF8C-B159-4D6A-9D61-9C2400A986E3,652,2009-06-10 10:17:13,2009-06-10 10:17:13,0,0,319.5582,Kai,True,...,319.5436,220.4200,0.00,0.00,1,146.9966,0.0000,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134524,2020-01-27,A9C9EF0F-4E79-4930-BA8A-A4130077FCC2,283484,2015-01-02 16:31:36,2015-01-02 16:31:36,2515,0,485.0000,BO73K5A6A,True,...,2308.1900,0.0000,0.00,0.00,0,0.0000,0.0000,0,NaN,NaN
134525,2020-01-27,787345C2-7606-4F72-8FE2-A4170082D77C,285168,2015-01-05 16:14:26,2015-01-05 16:14:26,1880,0,1120.0000,BO311A49,False,...,3000.0000,1990.0300,0.00,0.00,1,3000.0000,389.3600,0,NaN,NaN
134526,2020-01-27,E2D3384D-289A-4B4D-A2DA-A40F00F7C755,281602,2015-01-02 14:04:27,2015-01-02 14:04:27,1975,0,525.0000,BO41K639A,True,...,1869.7600,199.3300,630.24,1227.98,0,0.0000,0.0000,0,0.0,60.0
134527,2020-01-27,7CC7AB74-995B-4467-958A-A41700F78D59,285431,2015-01-05 16:56:12,2015-01-05 16:56:12,1840,0,1160.0000,BO45A925,False,...,2257.5400,561.5300,0.00,0.00,1,500.0000,96.8000,0,NaN,NaN
134528,2020-01-27,3A0DEBF3-292C-4EB4-B71A-A4170157749D,285630,2015-01-06 11:07:06,2015-01-06 11:07:06,2990,0,10.0000,BO152923A,False,...,1473.9100,683.2100,1526.09,9019.04,1,2500.0000,242.6400,0,0.0,60.0

In [ ]:
# Convert date columns to datetime
date_cols = ['ReportAsOfEOD', 'ListedOnUTC', 'BiddingStartedOn', 'GracePeriodStart', 'GracePeriodEnd', 'NextPaymentDate', 'ReScheduledOn']
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [ ]:
dn['ActiveLateLastPaymentCategory'] = df['ActiveLateLastPaymentCategory'].fillna('Unknown')

/tmp/ipython-input-1120570527.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dn['ActiveLateLastPaymentCategory'] = df['ActiveLateLastPaymentCategory'].fillna('Unknown')

In [ ]:
num_cols = ['BidsPortfolioManager', 'BidsManual', 'PreviousEarlyRepaymentsCountBeforeLoan', 'NrOfScheduledPayments', 'NextPaymentNr']
for col in num_cols:
    dn[col] = pd.to_numeric(dn[col], errors='coerce')

/tmp/ipython-input-624173626.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dn[col] = pd.to_numeric(dn[col], errors='coerce')

In [ ]:
dn = dn.drop_duplicates(subset=['LoanId', 'LoanNumber'])

In [ ]:
dn['NewCreditCustomer'] = dn['NewCreditCustomer'].astype(bool)

In [ ]:
dn['BidsManual'] = dn['BidsManual'].fillna(dn['BidsManual'].median())

In [ ]:
dn

,ReportAsOfEOD,LoanId,LoanNumber,ListedOnUTC,BiddingStartedOn,BidsPortfolioManager,BidsApi,BidsManual,UserName,NewCreditCustomer,...,InterestAndPenaltyPaymentsMade,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsCountBeforeLoan,NextPaymentNr,NrOfScheduledPayments,ActiveLateLastPaymentCategory
0,2020-01-27,F0660C80-83F3-4A97-8DA0-9C250112D6EC,659,2009-06-11 16:40:39,2009-06-11 16:40:39,0,0,115.0410,KARU,True,...,20.4222,0.00,0.00,1,83.0852,0.0000,0,NaN,NaN,Unknown
1,2020-01-27,978BB85B-1C69-4D51-8447-9C240104A3A2,654,2009-06-10 15:48:57,2009-06-10 15:48:57,0,0,140.6057,koort681,False,...,2.0227,0.00,0.00,2,255.6467,258.6256,0,NaN,NaN,Unknown
2,2020-01-27,EA44027E-7FA7-4BB2-846D-9C1F013C8A22,641,2009-06-05 19:12:29,2009-06-05 19:12:29,0,0,319.5580,0ie,True,...,59.7626,116.35,414.07,0,0.0000,0.0000,0,NaN,NaN,Unknown
3,2020-01-27,CE67AD25-2951-4BEE-96BD-9C2700C61EF4,668,2009-06-13 12:01:20,2009-06-13 12:01:20,0,0,57.5205,Alyona,True,...,18.7323,0.00,0.00,1,134.2144,0.0000,0,NaN,NaN,Unknown
4,2020-01-27,9408BF8C-B159-4D6A-9D61-9C2400A986E3,652,2009-06-10 10:17:13,2009-06-10 10:17:13,0,0,319.5582,Kai,True,...,220.4200,0.00,0.00,1,146.9966,0.0000,0,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134524,2020-01-27,A9C9EF0F-4E79-4930-BA8A-A4130077FCC2,283484,2015-01-02 16:31:36,2015-01-02 16:31:36,2515,0,485.0000,BO73K5A6A,True,...,0.0000,0.00,0.00,0,0.0000,0.0000,0,NaN,NaN,Unknown
134525,2020-01-27,787345C2-7606-4F72-8FE2-A4170082D77C,285168,2015-01-05 16:14:26,2015-01-05 16:14:26,1880,0,1120.0000,BO311A49,False,...,1990.0300,0.00,0.00,1,3000.0000,389.3600,0,NaN,NaN,Unknown
134526,2020-01-27,E2D3384D-289A-4B4D-A2DA-A40F00F7C755,281602,2015-01-02 14:04:27,2015-01-02 14:04:27,1975,0,525.0000,BO41K639A,True,...,199.3300,630.24,1227.98,0,0.0000,0.0000,0,0.0,60.0,Unknown
134527,2020-01-27,7CC7AB74-995B-4467-958A-A41700F78D59,285431,2015-01-05 16:56:12,2015-01-05 16:56:12,1840,0,1160.0000,BO45A925,False,...,561.5300,0.00,0.00,1,500.0000,96.8000,0,NaN,NaN,Unknown
134528,2020-01-27,3A0DEBF3-292C-4EB4-B71A-A4170157749D,285630,2015-01-06 11:07:06,2015-01-06 11:07:06,2990,0,10.0000,BO152923A,False,...,683.2100,1526.09,9019.04,1,2500.0000,242.6400,0,0.0,60.0,Unknown

In [ ]:
# For numerical columns: fill missing values with median and convert to numeric
num_cols = dn.select_dtypes(include=['float64', 'int64']).columns
for col in num_cols:
    median_val = dn[col].median()
    dn[col] = pd.to_numeric(dn[col], errors='coerce').fillna(median_val)

# For categorical columns: fill missing values with mode
cat_cols = dn.select_dtypes(include=['object', 'category']).columns
for col in cat_cols:
    mode_val = dn[col].mode()
    if not mode_val.empty:
        dn[col] = dn[col].fillna(mode_val[0])

In [ ]:
null_counts = dn.isnull().sum()
print(null_counts)

ReportAsOfEOD                             0
LoanId                                    0
LoanNumber                                0
ListedOnUTC                               0
BiddingStartedOn                          0
                                         ..
PreviousRepaymentsBeforeLoan              0
PreviousEarlyRepaymentsCountBeforeLoan    0
NextPaymentNr                             0
NrOfScheduledPayments                     0
ActiveLateLastPaymentCategory             0
Length: 78, dtype: int64

In [ ]:
for col, count in null_counts.items():
    print(f"{col}: {count}")

ReportAsOfEOD: 0
LoanId: 0
LoanNumber: 0
ListedOnUTC: 0
BiddingStartedOn: 0
BidsPortfolioManager: 0
BidsApi: 0
BidsManual: 0
UserName: 0
NewCreditCustomer: 0
LoanApplicationStartedDate: 0
LoanDate: 0
FirstPaymentDate: 0
MaturityDate_Original: 0
MaturityDate_Last: 0
ApplicationSignedHour: 0
ApplicationSignedWeekday: 0
VerificationType: 0
LanguageCode: 0
Age: 0
DateOfBirth: 0
Gender: 0
Country: 0
AppliedAmount: 0
Amount: 0
Interest: 0
LoanDuration: 0
MonthlyPayment: 0
County: 0
City: 0
UseOfLoan: 0
Education: 0
MaritalStatus: 0
EmploymentStatus: 0
EmploymentDurationCurrentEmployer: 0
OccupationArea: 0
HomeOwnershipType: 0
IncomeFromPrincipalEmployer: 0
IncomeFromPension: 0
IncomeFromFamilyAllowance: 0
IncomeFromSocialWelfare: 0
IncomeFromLeavePay: 0
IncomeFromChildSupport: 0
IncomeOther: 0
IncomeTotal: 0
ExistingLiabilities: 0
LiabilitiesTotal: 0
RefinanceLiabilities: 0
DebtToIncome: 0
FreeCash: 0
MonthlyPaymentDay: 0
ActiveScheduleFirstPaymentReached: 0
PlannedInterestTillDate: 0
LastPaymentOn: 0
ExpectedLoss: 0
LossGivenDefault: 0
ExpectedReturn: 0
ProbabilityOfDefault: 0
PrincipalOverdueBySchedule: 0
RecoveryStage: 0
StageActiveSince: 0
ModelVersion: 0
Rating: 0
Status: 0
Restructured: 0
WorseLateCategory: 0
CreditScoreEsMicroL: 0
PrincipalPaymentsMade: 0
InterestAndPenaltyPaymentsMade: 0
PrincipalBalance: 0
InterestAndPenaltyBalance: 0
NoOfPreviousLoansBeforeLoan: 0
AmountOfPreviousLoansBeforeLoan: 0
PreviousRepaymentsBeforeLoan: 0
PreviousEarlyRepaymentsCountBeforeLoan: 0
NextPaymentNr: 0
NrOfScheduledPayments: 0
ActiveLateLastPaymentCategory: 0